### ISSUE TITLE
Kerberos support

### ISSUE THREAD

**Issue by brunowego** [s-t-e-a-l-t-h/pyopentsdb#2]
Nice lib @s-t-e-a-l-t-h congrats!

Do you have any plan to support krb5? Thanks.

**Comment by mikecokina** [comment]
Thank you.

Currently, there is no intention to support Kerberos.
But, I quickly looked into, and there is something like requests-kerberos
package, so in case of simple integration
I will consider to extend it.

po 24. 12. 2018 o 11:51 Bruno Wego <notifications@github.com> napísal(a):

**Comment by brunowego** [comment]
Thanks @s-t-e-a-l-t-h 👍
